apiVersion: v1
kind: Service
metadata:
  name: chronograf
  labels:
    app: chronograf
spec:
  ports:
    - port: 80
      name: chronograf-dashboard
      targetPort: 8888
  selector:
    app: chronograf
  type: LoadBalancer
<<<<<<< HEAD
  loadBalancerIP: "35.224.165.101"
=======
  loadBalancerIP: "X.X.X.X"
>>>>>>> ad07dda13e5eff67a7eb1e6e6a7a688b73c1a3ed
