apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    k8s-app: elasticsearch
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: 9200
    name: api
    targetPort: 9200
  - port: 9300
    name: extra
    targetPort: 9300
  selector:
    k8s-app: elasticsearch
  type: LoadBalancer
