kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-configmap
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  fluent.conf: |-
    <source>
      @type tail
      path /var/log/nginx/access.log #...or where you placed your Apache access log
      pos_file /var/log/nginx_access-error.log.pos # This is where you record file position
      tag nginx
      format nginx # Do you have a custom format? You can write your own regex.
      format multiline
      format_firstline /^\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2} \[\w+\] (?<pid>\d+).(?<tid>\d+): /
      format1 /^(?<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?<log_level>\w+)\] (?<pid>\d+).(?<tid>\d+): (?<message>.*)/
      multiline_flush_interval 3s
    </source>

    <match **>
      @type elasticsearch
      host 35.224.115.181 #(optional; default="localhost")
      port 9200 #(optional; default=9200)
      index_name new #(optional; default=fluentd)
      type_name jmeter #(optional; default=fluentd)
    </match>
