apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  ports:
    - port: 8086
      name: api
      targetPort: 8086
  selector:
    app: influxdb
  type: LoadBalancer
#  loadBalancerIP: "X.X.X.X"
