apiVersion: v1
kind: Service
metadata:
  name: kapacitor
  labels:
    app: jmeter-kapacitor
spec:
  ports:
    - port: 9092
      name: kapacitor-api
      targetPort: 9092
  selector:
    app: jmeter-kapacitor
  type: LoadBalancer
  loadBalancerIP: "X.X.X.X"
