apiVersion: v1
kind: Service
metadata:
  name: kapacitor
  labels:
    app: kapacitor
spec:
  ports:
    - port: 9092
      name: kapacitor-api
      targetPort: 9092
  selector:
    app: kapacitor
  type: LoadBalancer
  loadBalancerIP: "35.193.145.223"
