apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
      - name: jmmaster
        image: softcrylicqa/jmeter-master
        volumeMounts:
          - name: loadtest
            mountPath: /load_test
            subPath: "load_test"
          - name: config-volume
            mountPath: /etc/td-agent
        ports:
        - containerPort: 60000
        - containerPort: 24224
        - containerPort: 5140
      volumes:
      - name: loadtest 
        configMap:
         name: jmeter-load-test
      - name: config-volume
        configMap:
          name: jmeter-fluentd-configmap
